run:
	cd kernel;make run
build:
	cd kernel;make build
asm:
	cd kernel;make asm
debug:
	cd kernel;make debug
gdb:
	cd kernel;make gdb
user:
	cd user_c;make build
all: user run

clean:
	cd kernel;cargo clean