[package]
name = "os"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xmas-elf = "0.9.0"
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
bitflags = "1.2.1"
buddy_system_allocator = "0.6"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
sbi-rt = { version = "0.0.2", features = ["legacy"] }
spin = "0.9"
libc = { version = "0.2", optional = true }
hashbrown = "0.13.2"
[dev-dependencies]
tempfile = "3.2"

[target.'cfg(windows)'.dependencies]
filetime = "0.2"
winapi = "0.3"

[features]
std = ["libc"]
